flasher:
  plugins:
    noty:
      scripts:
        - "/vendor/flasher/jquery.min.js"
        - "/vendor/flasher/toastr.min.js"
        - "/vendor/flasher/flasher-toastr.min.js"
      styles:
        - "/vendor/flasher/toastr.min.css"
      options:
        # Optional: Add global options here
        closeButton: true
